# 关节力矩限幅
TORQUE_LIMIT: [85.0, 85.0, 85.0, 85.0, 85.0, 30.0, 30.0,    85.0, 85.0, 85.0, 85.0, 85.0, 30.0, 30.0,    10.0, 10.0]
# 外力矩观测器参数
NDO_GAIN: [10, 10, 10, 10, 10, 10, 10,   10, 10, 10, 10, 10, 10, 10,   10.0, 10.0]
# 阻抗控制参数（硬）
# KP: [500, 500, 500, 60, 100, 40, 40,   500, 500, 500, 60, 100, 40, 40,   100.0, 100.0] 
# KD: [20, 20, 20, 15, 10, 3, 3,   20, 20, 20, 15, 10, 3, 3,   4, 4]
# 阻抗控制参数(软)
# KP: [100, 100, 100, 100, 60, 40, 40,   100, 100, 100, 100, 60, 40, 40,   100.0, 100.0] 
# KD: [10, 10, 10, 10, 10, 3, 3,   10, 10, 10, 10, 10, 3, 3,   4, 4]
# # 力控轨迹跟踪(ndo)
KP: [1000, 400, 500, 400, 500, 70, 70,   1000, 800, 500, 500, 500, 70, 40,   100.0, 100.0]
KD: [25, 15, 35, 15, 20, 4, 4,   23, 25, 25, 15, 20, 4, 4,   4, 4]
# 拖动示教参数
K_TEACH: [200, 200, 200, 200, 200, 200, 200,   200, 200, 200, 200, 200, 200, 200,   200, 200] # 边界弹性
D_TEACH: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,   0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,   0.1, 0.1] # 阻尼