# 关节力矩限幅
TORQUE_LIMIT : [85.0, 85.0, 85.0, 85.0, 85.0, 85.0, 30.0, 30.0,   85.0, 85.0, 85.0, 85.0, 85.0, 85.0, 30.0, 30.0,   10.0, 10.0,  180.0, 180.0, 180.0, 180.0]

# 外力矩观测器参数
NDO_GAIN: [10, 10, 10, 10, 10, 10, 10, 10,   10, 10, 10, 10, 10, 10, 10, 10,   10.0, 10.0,   10.0, 10.0, 10.0, 10.0]

# 关节碰撞检测力矩阈值
JOINT_COLLISION_THRESHOLD: [10, 10, 10, 10, 10, 10, 10, 10,   10, 10, 10, 10, 10, 10, 10, 10,   10.0, 10.0,  10.0, 10.0, 10.0, 10.0]

# 力控轨迹跟踪参数
KP: [1000, 1000, 800, 600, 500, 500, 70, 70,   1000, 1000, 800, 600, 500, 500, 70, 70,   100.0, 100.0,  100.0, 100.0, 100.0, 100.0]
KD: [25, 25, 20, 40, 25, 25, 4, 4,   25, 25, 20, 40, 25, 25, 4, 4,   4, 4,  4, 4, 4, 4]

# # 阻抗控制参数（硬）
# K_IMPDC: [500, 500, 500, 500, 60, 100, 40, 40,   500, 500, 500, 500, 60, 100, 40, 40,   100.0, 100.0,  100.0, 100.0, 100.0, 100.0] 
# D_IMPDC: [20, 20, 20, 20, 15, 10, 3, 3,   20, 20, 20, 20, 15, 10, 3, 3,   4, 4,  4, 4, 4, 4]

# 阻抗控制参数(软)
K_IMPDC: [100, 100, 100, 100, 100, 60, 40, 40,   100, 100, 100, 100, 100, 60, 40, 40,   100.0, 100.0,  100.0, 100.0, 100.0, 100.0] 
D_IMPDC: [10, 10, 10, 10, 10, 10, 3, 3,    10, 10, 10, 10, 10, 10, 3, 3,   4, 4,  4, 4, 4, 4]

# 拖动示教参数
K_TEACH: [200, 200, 200, 200, 200, 200, 200, 200,   200, 200, 200, 200, 200, 200, 200, 200,   200, 200,  300, 300, 300, 300] # 弹性
D_TEACH: [0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,   0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,   0.1, 0.1,  0.1, 0.1, 0.1, 0.1] # 阻尼

# 碰撞保护参数
K_PROTECT: [200, 200, 200, 200, 200, 200, 200, 200,   200, 200, 200, 200, 200, 200, 200, 200,   200, 200,  300, 300, 300, 300] # 边界弹性
D_PROTECT: [15.0, 15.0, 15.0, 15.0, 8.0, 8.0, 4.0, 4.0,  15.0, 15.0, 15.0, 15.0, 8.0, 8.0, 4.0, 4.0,   5.0, 5.0,  25.0, 25.0, 25.0, 25.0] # 阻尼