# 关节力矩限幅
TORQUE_LIMIT: [85.0, 85.0, 85.0, 85.0,    85.0, 85.0, 85.0, 85.0,  10.0, 10.0]

# 外力矩观测器参数
NDO_GAIN: [10, 10, 10, 10,   10, 10, 10, 10,  10, 10]

# 关节碰撞检测力矩阈值
JOINT_COLLISION_THRESHOLD: [10, 10, 10, 10,   10, 10, 10, 10,   10.0, 10.0]

# 力控轨迹跟踪参数
KP: [1000, 800, 600, 500,   1000, 800, 600, 500,   100.0, 100.0]
KD: [25, 20, 40, 25,   25, 20, 40, 25,   4, 4]

# # 阻抗控制参数（硬）
# K_IMPDC: [500, 500, 500, 60,   500, 500, 500, 60,  100.0, 100.0] 
# D_IMPDC: [20, 20, 20, 15,   20, 20, 20, 15,   4, 4]

# 阻抗控制参数(软)
K_IMPDC: [100, 100, 100, 60,   100, 100, 100, 60,  100.0, 100.0] 
D_IMPDC: [10, 10, 10, 10,  10, 10, 10, 10,   4, 4]

# 拖动示教参数
K_TEACH: [200, 200, 200, 200,   200, 200, 200, 200,   200, 200] # 边界弹性
D_TEACH: [0.1, 0.1, 0.1, 0.1,   0.1, 0.1, 0.1, 0.1,   0.1, 0.1] # 阻尼

# 碰撞保护参数
K_PROTECT: [200, 200, 200, 200,   200, 200, 200, 200,   200, 200] # 边界弹性
D_PROTECT: [15.0, 15.0, 15.0, 8.0,  15.0, 15.0, 15.0, 8.0,   5.0, 5.0] # 阻尼