TORQUE_LIMIT : [85.0, 85.0, 85.0, 85.0,  85.0, 85.0, 85.0, 85.0,  10.0, 10.0,  100.0, 100.0, 100.0]
NDO_GAIN : [12, 12, 10, 10,  12, 12, 10, 10,  10.0, 10.0,  12, 12, 12]
KP: [1000, 2000, 2000, 1200,  1000, 2000, 2000, 1200,  100.0, 100.0,  1000.0, 1000.0, 1000.0]
KD: [30, 25, 25, 15,  30, 25, 25, 15,  4, 4,  20, 20, 20]
LOW_PASS_ALPHA_TAU: [0.8, 0.8, 0.8, 0.8,  0.8, 0.8, 0.8, 0.8,  0.8, 0.8,  0.8, 0.8, 0.8]
LOW_PASS_ALPHA_VEL: [0.8, 0.8, 0.8, 1.0,  0.8, 0.8, 0.8, 1.0,  0.8, 0.8,  0.8, 0.8, 0.8]