URDF_FILE: /home/nav01/Documents/uplimlibrary/models/WA3.urdf
JOINTS_LIST:
  - Shoulder_Z_L:
      pos_limit: [-0.349, 0.349]
      offset_vel: 0
      driverNum: 0
      algNum: 0
  - Shoulder_Y_L:
      pos_limit: [-3.197, 1.145]
      offset_vel: 0
      driverNum: 1
      algNum: 1
  - Shoulder_X_L:
      pos_limit: [-0.020, 3.026]
      offset_vel: 0
      driverNum: 2
      algNum: 2
  - Elbow_Z_L:
      pos_limit: [-2.830, 2.830]
      offset_vel: 0
      driverNum: 3
      algNum: 3
  - Elbow_Y_L:
      pos_limit: [-2.000, 0.070]
      offset_vel: 0
      driverNum: 4
      algNum: 4
  - Wrist_Z_L:
      pos_limit: [-2.855, 2.855]
      offset_vel: 0
      driverNum: 5
      algNum: 5
  - Wrist_Y_L:
      pos_limit: [-1.487, 1.487]
      offset_vel: 1
      driverNum: 6
      algNum: 6
  - Wrist_X_L:
      pos_limit: [-1.487, 1.487]
      offset_vel: 1
      driverNum: 7
      algNum: 7
  - Shoulder_Z_R:
      pos_limit: [ -0.349, 0.349 ]
      offset_vel: 0
      driverNum: 8
      algNum: 8
  - Shoulder_Y_R:
      pos_limit: [-3.197, 1.145]
      offset_vel: 0
      driverNum: 9
      algNum: 9
  - Shoulder_X_R:
      pos_limit: [-3.026, 0.02]
      offset_vel: 0
      driverNum: 10
      algNum: 10
  - Elbow_Z_R:
      pos_limit: [-2.830, 2.830]
      offset_vel: 0
      driverNum: 11
      algNum: 11
  - Elbow_Y_R:
      pos_limit: [-2.000, 0.070]
      offset_vel: 0
      driverNum: 12
      algNum: 12
  - Wrist_Z_R:
      pos_limit: [-2.855, 2.855]
      offset_vel: 0
      driverNum: 13
      algNum: 13
  - Wrist_Y_R:
      pos_limit: [-1.487, 1.487]
      offset_vel: 1
      driverNum: 14
      algNum: 14
  - Wrist_X_R:
      pos_limit: [-1.487, 1.487]
      offset_vel: 1
      driverNum: 15
      algNum: 15
  - Neck_Z:
      pos_limit: [-0.785, 0.785]
      offset_vel: 1
      driverNum: 16
      algNum: 16  
  - Neck_Y:
      pos_limit: [-0.174, 0.349]
      offset_vel: 1
      driverNum: 17
      algNum: 17     
  - Pitch_Y_B:
      pos_limit: [-1.047, 1.047]
      offset_vel: 0
      driverNum: 18
      algNum: 18
  - Pitch_Y_M:
      pos_limit: [-2.443, 2.443]
      offset_vel: 0
      driverNum: 19
      algNum: 19 
  - Waist_Z:
      pos_limit: [-2.094, 3.228]
      offset_vel: 0
      driverNum: 20
      algNum: 20   
  - Waist_Y:
      pos_limit: [-0.959, 0.959]
      offset_vel: 0
      driverNum: 21
      algNum: 21         

POSITION_THRESHOLD: 0.005